-- ============================================================
-- MIGRACION 016: tabla notificaciones_cotizacion + validacion de FK
--
-- 1. Crea la tabla notificaciones_cotizacion que el codigo ya
--    consulta e inserta (registro de notificaciones de cotizacion
--    "lista para recojo" enviadas al cliente). Sin esta tabla el
--    registro fallaba en silencio (try/catch) y no se guardaba nada.
-- 2. Valida las dos FK que estaban en estado NOT VALID, una vez
--    confirmado que no existen filas huerfanas.
--
-- Idempotente.
-- ============================================================
BEGIN;

-- 1. Tabla de intentos de notificacion por cotizacion.
CREATE TABLE IF NOT EXISTS notificaciones_cotizacion (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_cotizacion integer NOT NULL,
  tipo          character varying(40) NOT NULL,
  email_destino character varying(255),
  estado        character varying(20) NOT NULL DEFAULT 'pendiente',
  payload       jsonb NOT NULL DEFAULT '{}'::jsonb,
  respuesta     jsonb,
  mensaje_error text,
  fecha_intento timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_envio   timestamp without time zone,
  CONSTRAINT notificaciones_cotizacion_estado_check
    CHECK ((estado)::text = ANY (ARRAY[
      'pendiente'::character varying,
      'enviada'::character varying,
      'fallida'::character varying
    ]::text[])),
  CONSTRAINT notificaciones_cotizacion_id_cotizacion_fkey
    FOREIGN KEY (id_cotizacion) REFERENCES cotizaciones(id) ON DELETE CASCADE
);

-- Indice para el LATERAL que busca el ultimo intento por cotizacion.
CREATE INDEX IF NOT EXISTS idx_notif_cotizacion_intento
  ON notificaciones_cotizacion (id_cotizacion, fecha_intento DESC);

-- 2. Validar las FK que estaban NOT VALID (sin filas huerfanas confirmado).
ALTER TABLE detalle_cotizacion
  VALIDATE CONSTRAINT fk_detalle_producto;

ALTER TABLE historial_precios_producto
  VALIDATE CONSTRAINT fk_historial_producto;

COMMIT;
